# fly.toml app configuration file generated for contents-hub on 2025-12-06T14:38:03+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'contents-hub'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile.server'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  APP_ENV = 'production'
  PORT = '3000'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
